version: '3'
services:
  python-flask-dev-file-none:
    build:
      context: ""
      dockerfile: python-flask/Dockerfile
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./conf/file-none.yml:/app/conf.yml"
  python-flask-dev-file-preload:
    build:
      context: ""
      dockerfile: python-flask/Dockerfile
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./conf/file-preload.yml:/app/conf.yml"
  python-tornado-tornado-file-none:
    build:
      context: ""
      dockerfile: python-tornado/Dockerfile
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./conf/file-none.yml:/app/conf.yml"
  python-tornado-tornado-file-preload:
    build:
      context: ""
      dockerfile: python-tornado/Dockerfile
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./conf/file-preload.yml:/app/conf.yml"
  wrk:
    build:
      context: ""
      dockerfile: wrk/Dockerfile
    volumes:
      - ".:/results"
    command: -c64 -d5s -t8 -s urls.lua http://python-tornado-tornado-file-preload/
