version: '3'
services:
  flask-dev-file-none:
    build:
      context: ""
      dockerfile: python-flask/Dockerfile
    ports:
      - 80:5000
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./conf/file-none.yml:/app/conf.yml"
  flask-dev-file-preload:
    build:
      context: ""
      dockerfile: python-flask/Dockerfile
    ports:
      - 80:5000
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./conf/file-preload.yml:/app/conf.yml"
  tornado-file-none:
    build:
      context: ""
      dockerfile: python-tornado/Dockerfile
    ports:
      - 80:8888
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./conf/file-none.yml:/app/conf.yml"
  tornado-file-preload:
    build:
      context: ""
      dockerfile: python-tornado/Dockerfile
    ports:
      - 80:8888
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./conf/file-preload.yml:/app/conf.yml"
