version: '3'
services:
  json-file-ristretto:
    image: tivvit/shush:0.0.1
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./json-file-ristretto.yml:/app/conf.yml"
  json-file-lru:
    image: tivvit/shush:0.0.1
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./json-file-lru.yml:/app/conf.yml"
  json-file-big:
    image: tivvit/shush:0.0.1
    volumes:
      - "../utils/urls.json:/app/urls.json"
      - "./json-file-big.yml:/app/conf.yml"
  wrk:
    build:
      context: "../speed-tests"
      dockerfile: wrk/Dockerfile
    volumes:
      - ".:/results"
    command: -c64 -d5s -t8 -s urls.lua http://json-file-ristretto/